name       : python-grpcio
version    : 1.21.1
release    : 2
source     :
    - https://files.pythonhosted.org/packages/fb/d5/30bc142a40bb891c28739ec48c99730d20e5fb9cf9637036b4b52f70505b/grpcio-1.21.1.tar.gz : fb98dbfee0d963b49ae5754554028cf62e6bd695f22de16d242ba9d2f0b7339b
license    : Apache-2.0
component  : programming.python
summary    : HTTP/2-based RPC framework
description: |
    HTTP/2-based RPC framework
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
