name       : python-grpcio
version    : 1.27.2
release    : 4
source     :
    - https://files.pythonhosted.org/packages/74/52/9204d08bf37ac2505ebab2fa93b808fac87564580d7cc839db2fe11c3bdd/grpcio-1.27.2.tar.gz : 5ae532b93cf9ce5a2a549b74a2c35e3b690b171ece9358519b3039c7b84c887e
license    : Apache-2.0
component  : programming.python
summary    : HTTP/2-based RPC framework
description: |
    HTTP/2-based RPC framework
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
