name       : python-grpcio
version    : 1.41.1
release    : 8
source     :
    - https://pypi.io/packages/source/g/grpcio/grpcio-1.41.1.tar.gz : 9b751271b029432a526a4970dc9b70d93eb6f0963b6a841b574f780b72651969
license    : Apache-2.0
component  : programming.python
summary    : HTTP/2-based RPC framework
description: |
    HTTP/2-based RPC framework
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
